/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("de.rwth.procmin.tb.java-library")
}

group = "${group}.core"

dependencies {
  implementation("org.apache.logging.log4j:log4j-core:2.22.0")
  implementation("org.apache.logging.log4j:log4j-api:2.22.0")

  // Parsing XES logs
  implementation(group = "prom", name = "XESLite", version = "latest", configuration = "default") {
    exclude(group = "log4j", module = "log4j")
    exclude(group = "prom-libs", module = "jgrapht")
  }

  implementation(group = "prom", name = "PetriNets", version = "latest", configuration = "default") {
    exclude(group = "log4j", module = "log4j")
    exclude(group = "prom-libs", module = "jgrapht")
    exclude(group = "org.python", module = "jython-standalone")
    exclude(group = "xml-apis", module = "xml-apis")
  }

  // Third party
  implementation(group = "com.google.guava", name = "guava", version = "31.1-jre")
}

